=== KrishnaAmbili/micandroid/trunk/lightportald/WebContent/WEB-INF/portal-layout.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- 
 * Light Portal
 *
 * Copyright (c) 2009, Light Portal, Inc or third-party contributors as
 * indicated by the @author tags or express copyright attribution
 * statements applied by the authors.  All third-party contributions are
 * distributed under license by Light Portal, Inc.
 *
 * This copyrighted material is made available to anyone wishing to use, modify,
 * copy, or redistribute it subject to the terms and conditions of the GNU
 * Lesser General Public License, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this distribution; if not, write to:
 * Free Software Foundation, Inc.
 * 51 Franklin Street, Fifth Floor
 * Boston, MA  02110-1301  USA
 *
 */
-->
<!--W3C Schema generated by XMLSpy v2006 rel. 3 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="notCloseable">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>	
	<xs:element name="noEditMode">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="noConfigMode">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="between">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="closeable">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="editable">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="moveable">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="allowAddContent">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="color" type="xs:string"/>
	<xs:element name="column">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="defaulted">
		<xs:simpleType>
			<xs:restriction base="xs:boolean"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="portalLayout">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="portalUser" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="portalTab">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element ref="url" minOccurs="0"/>
				<xs:element ref="defaulted"/>
				<xs:element ref="closeable"/>
				<xs:element ref="editable"/>
				<xs:element ref="moveable"/>
				<xs:element ref="allowAddContent"/>
				<xs:element ref="widths"/>
				<xs:element ref="between"/>
				<xs:element ref="portletWindow"/>
				<xs:element ref="color" minOccurs="0"/>
				<xs:element ref="portalTab" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="portlets" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="portalUser">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="portalTab" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="user">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="role">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="portlet">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="column"/>
				<xs:element ref="row"/>
				<xs:element ref="notCloseable" minOccurs="0"/>
				<xs:element ref="noEditMode" minOccurs="0"/>
				<xs:element ref="noConfigMode" minOccurs="0"/>
				<xs:element ref="barBgColor" minOccurs="0"/>
				<xs:element ref="barFontColor" minOccurs="0"/>
				<xs:element ref="contentBgColor" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="portletWindow">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="portlets">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="portlet" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="row">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="title">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="url" type="xs:anyURI"/>
	<xs:element name="widths">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="barBgColor">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="barFontColor">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="contentBgColor">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== KrishnaAmbili/micandroid/lightportald/WebContent/WEB-INF/portal-layout.xml
<?xml version="1.0" encoding="UTF-8"?>
<portalLayout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="portal-layout.xsd">
	<portalUser role="role_guest">		
		<portalTab>
			<title>tab.title.home</title>			
			<defaulted>true</defaulted>
			<closeable>false</closeable>
			<editable>false</editable>
			<moveable>false</moveable>
			<allowAddContent>false</allowAddContent>
			<widths>700,300</widths>
			<between>10</between>
			<portletWindow>WindowSkin2</portletWindow>			
			<portlets>
				<portlet>
					<name>infoPortlet</name>
					<column>0</column>
					<row>0</row>
					<notCloseable>true</notCloseable>
					<noEditMode>true</noEditMode>
					<noConfigMode>true</noConfigMode>					
				</portlet>
				
			    <portlet>
					<name>loginPortlet</name>
					<column>1</column>
					<row>0</row>
					<notCloseable>true</notCloseable>
					<noEditMode>true</noEditMode>
					<noConfigMode>true</noConfigMode>
				</portlet>																													
			</portlets>
		</portalTab>	
	</portalUser>
	
	<portalUser role="role_user">
		<portalTab>
		   <title>tab.title.personal</title>   
		   <defaulted>true</defaulted>
		   <closeable>false</closeable>
		   <editable>true</editable>
		   <moveable>true</moveable>
		   <allowAddContent>true</allowAddContent>
		   <widths>300,700</widths>
		   <between>10</between>
		   <portletWindow>WindowSkin2</portletWindow>   
		   <portlets>
			    <portlet>
			     <name>profilePortlet</name>
			     <column>0</column>
			     <row>0</row>
			    </portlet> 	  	    		
			    <portlet>
			     <name>myMessagePortlet</name>
			     <column>0</column>
			     <row>1</row>
			    </portlet>        
		        <portlet>        
			     <name>friendsPortlet</name>
			     <column>0</column>
			     <row>2</row>
		    	</portlet> 		    	       
			    <portlet>
					<name>microblogAddPortlet</name>
					<column>1</column>
					<row>0</row>
				</portlet>		
				<portlet>
			     <name>microblogPortlet</name>
			     <column>1</column>
			     <row>1</row>
			    </portlet> 
			</portlets>	 	    
	  	</portalTab>	   
	</portalUser>
	
		<portalUser role="role_noprofile">
	  	<portalTab>
		   <title>tab.title.profile</title>   
		   <defaulted>true</defaulted>
		   <closeable>false</closeable>
		   <editable>false</editable>
		   <moveable>false</moveable>
		   <allowAddContent>false</allowAddContent>
		   <widths>300,700</widths>
		   <between>10</between>
		   <portletWindow>WindowSkin2</portletWindow>   
		   <portlets>
			    <portlet>
			     <name>profilePortlet</name>
			     <column>0</column>
			     <row>0</row>
			    </portlet> 	  	
			    <portlet>
			     <name>myContactPortlet</name>
			     <column>0</column>
			     <row>1</row>
			    </portlet> 		    		
		   </portlets>	 	    
	  </portalTab>    	
	</portalUser>	
	<portalUser role="role_profile">
	  	<portalTab>
		   <title>tab.title.profile</title>   
		   <defaulted>true</defaulted>
		   <closeable>false</closeable>
		   <editable>false</editable>
		   <moveable>false</moveable>
		   <allowAddContent>false</allowAddContent>
		   <widths>300,700</widths>
		   <between>10</between>
		   <portletWindow>WindowSkin2</portletWindow>   
		   	<portlets>
			    <portlet>
			     <name>profilePortlet</name>
			     <column>0</column>
			     <row>0</row>
			    </portlet> 	  	    		
			    <portlet>
			     <name>myBlurbPortlet</name>
			     <column>0</column>
			     <row>1</row>
			    </portlet>        
		        <portlet>        
			     <name>friendsPortlet</name>
			     <column>0</column>
			     <row>2</row>
			    </portlet> 
			    <portlet>
			     <name>myContactPortlet</name>
			     <column>0</column>
			     <row>3</row>
			    </portlet> 		 	        
			    <portlet>
					<name>microblogAddPortlet</name>
					<column>1</column>
					<row>0</row>
				</portlet>		
				<portlet>
			     <name>microblogPortlet</name>
			     <column>1</column>
			     <row>1</row>
			    </portlet> 
		   	</portlets>	 	   
		  </portalTab>    	
	</portalUser>	
	
	<portalUser role="role_group">
	  <portalTab>
	   <title>tab.title.group</title>   
	   <defaulted>true</defaulted>
	   <closeable>true</closeable>
	   <editable>true</editable>
	   <moveable>true</moveable>
	   <allowAddContent>true</allowAddContent>
	   <widths>300,400,240</widths>
	   <between>10</between>
	   <portletWindow>WindowSkin2</portletWindow>   
	   <portlets>
	    <portlet>
	     <name>groupProfilePortlet</name>
	     <column>0</column>
	     <row>0</row>
	     <notCloseable>true</notCloseable>
	    </portlet> 	  	 
	    <portlet>
	     <name>activityPortlet</name>
	     <column>1</column>
	     <row>0</row>
	     <notCloseable>true</notCloseable>
	    </portlet> 
	    <portlet>
	     <name>groupMembersPortlet</name>
	     <column>2</column>
	     <row>0</row>
	     <notCloseable>true</notCloseable>
	    </portlet> 	     
	   </portlets>
	  </portalTab>  
	  <portalTab>
	   <title>tab.title.members</title>   
	   <defaulted>true</defaulted>
	   <closeable>true</closeable>
	   <editable>true</editable>
	   <moveable>true</moveable>
	   <allowAddContent>true</allowAddContent>
	   <widths>1000</widths>
	   <between>10</between>
	   <portletWindow>WindowSkin2</portletWindow>   
	   <portlets>
	    <portlet>
	     <name>groupMembersPortlet</name>
	     <column>0</column>
	     <row>0</row>
	     <notCloseable>true</notCloseable>
	    </portlet> 	  
	   </portlets>
	  </portalTab>  
	  <portalTab>
	   <title>tab.title.photos</title>   
	   <defaulted>true</defaulted>
	   <closeable>false</closeable>
	   <editable>false</editable>
	   <moveable>false</moveable>
	   <allowAddContent>false</allowAddContent>
	   <widths>1000</widths>
	   <between>10</between>
	   <portletWindow>WindowSkin2</portletWindow>   
	   <portlets>
	    <portlet>
	     <name>groupPicturePortlet</name>
	     <column>0</column>
	     <row>0</row>
	     <notCloseable>true</notCloseable>
	    </portlet> 	  
	   </portlets>
	  </portalTab> 
	  <portalTab>
	   <title>tab.title.blog</title>   
	   <defaulted>true</defaulted>
	   <closeable>true</closeable>
	   <editable>true</editable>
	   <moveable>true</moveable>
	   <allowAddContent>true</allowAddContent>
	   <widths>1000</widths>
	   <between>10</between>
	   <portletWindow>WindowSkin2</portletWindow>   
	   <portlets>
	    <portlet>
	     <name>blogGroupPortlet</name>
	     <column>0</column>
	     <row>0</row>
	     <notCloseable>true</notCloseable>
	    </portlet> 	       
	   </portlets>
	  </portalTab> 
	  <portalTab>
	   <title>tab.title.forum</title>   
	   <defaulted>true</defaulted>
	   <closeable>true</closeable>
	   <editable>true</editable>
	   <moveable>true</moveable>
	   <allowAddContent>true</allowAddContent>
	   <widths>1000</widths>
	   <between>10</between>
	   <portletWindow>WindowSkin2</portletWindow>   
	   <portlets>
	    <portlet>
	     <name>forumPortlet</name>
	     <column>0</column>
	     <row>0</row>
	     <notCloseable>true</notCloseable>
	    </portlet> 	       
	   </portlets>
	  </portalTab> 
	  <portalTab>
	   <title>tab.title.bulletin</title>   
	   <defaulted>true</defaulted>
	   <closeable>true</closeable>
	   <editable>true</editable>
	   <moveable>true</moveable>
	   <allowAddContent>true</allowAddContent>
	   <widths>1000</widths>
	   <between>10</between>
	   <portletWindow>WindowSkin2</portletWindow>   
	   <portlets>	     
	    <portlet>
	     <name>bulletinPortlet</name>
	     <column>0</column>
	     <row>1</row>
	     <notCloseable>true</notCloseable>
	    </portlet> 	          
	   </portlets>
	  </portalTab>	        	  	
	</portalUser>		
	<portalUser role="role_admin">
	  <portalTab>
	   <title>Admin</title>   
	   <defaulted>false</defaulted>
	   <closeable>false</closeable>
	   <editable>true</editable>
	   <moveable>true</moveable>
	   <allowAddContent>true</allowAddContent>
	   <widths>400,600</widths>
	   <between>10</between>
	   <portletWindow>WindowSkin2</portletWindow>   
	   <portlets>	    
	    <portlet>
	     <name>indexerPortlet</name>
	     <column>0</column>
	     <row>0</row>
	     <notCloseable>true</notCloseable>
	    </portlet>
	    <portlet>
			<name>internalNewsPortlet</name>
			<column>0</column>
			<row>1</row>
			<notCloseable>true</notCloseable>					
		</portlet>	 	      	 
	    <portlet>
	     <name>organizationPortlet</name>
	     <column>1</column>
	     <row>0</row>
	     <notCloseable>true</notCloseable>
	    </portlet> 
	    <portlet>
	     <name>userManagePortlet</name>
	     <column>1</column>
	     <row>1</row>
	     <notCloseable>true</notCloseable>
	    </portlet>	    
	   </portlets>	   
	  </portalTab>    	
	</portalUser>	
	<portalUser role="channel_forum">
		<portalTab>
			<title>tab.title.forum</title>			
			<defaulted>false</defaulted>
			<closeable>false</closeable>
			<editable>false</editable>
			<moveable>false</moveable>
			<allowAddContent>false</allowAddContent>
			<widths>1000</widths>
			<between>10</between>
			<portletWindow>WindowSkin2</portletWindow>
			<portlets>
				<portlet>
					<name>forumPortlet</name>
					<column>0</column>
					<row>0</row>
					<notCloseable>true</notCloseable>
					<noEditMode>true</noEditMode>
					<noConfigMode>true</noConfigMode>
				</portlet>	
			</portlets>
		</portalTab>
	</portalUser>
	<portalUser role="channel_blog">
		<portalTab>
			<title>tab.title.blog</title>			
			<defaulted>false</defaulted>
			<closeable>false</closeable>
			<editable>false</editable>
			<moveable>false</moveable>
			<allowAddContent>false</allowAddContent>
			<widths>1000</widths>
			<between>10</between>
			<portletWindow>WindowSkin1</portletWindow>
